from .auth import *
from .courses import *
from .feedback import *
from .news import *
from .other import *
from .school import *
from .sessions import *
from .students import *
from .trainers import *
from .register import *