# Generated by Django 5.0.1 on 2024-01-28 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseschedule',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='end_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='makeup',
            name='end_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 28, 14, 32, 23, 256957)),
        ),
    ]
