# Generated by Django 5.0.1 on 2024-06-26 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_invoice_invoice_date_time_alter_trainer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 15, 18, 59, 948747)),
        ),
    ]
