<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 5.0.1 on 2024-06-27 11:59
=======
# Generated by Django 5.0.1 on 2024-07-03 14:30
>>>>>>> fd39b54 (Fixed tests structure)
=======
# Generated by Django 5.0.1 on 2024-06-27 11:59
>>>>>>> b915ad0 (dummy commit)

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_invoice_invoice_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date_time',
<<<<<<< HEAD
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 11, 59, 20, 918)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 3, 14, 30, 57, 531073)),
>>>>>>> fd39b54 (Fixed tests structure)
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 27, 11, 59, 20, 918)),
>>>>>>> b915ad0 (dummy commit)
        ),
    ]
