# Generated by Django 5.0.1 on 2024-01-31 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_invoice_invoice_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysoff',
            name='day_off_info',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 21, 39, 56, 438501)),
        ),
    ]
