# Generated by Django 5.0.1 on 2024-01-31 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_invoice_invoice_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 21, 43, 45, 639549)),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='room name', max_length=50),
        ),
    ]
