# Generated by Django 5.0.1 on 2024-04-10 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_invoice_invoice_date_time_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 10, 18, 28, 26, 488591)),
        ),
    ]
